apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.Secret.Name }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .Values.Secret.ARN }}
          jmesPath:
          {{- range .Values.Secret.Vars }}
            - path: {{ . }}
              objectAlias: {{ . }}
          {{- end }}
  secretObjects:
    - secretName: {{ .Values.Secret.SecretName }}
      type: Opaque
      data:
        {{- range .Values.Secret.Vars }}
        - objectName: {{ . }}
            key: {{ . }}
        {{- end }}