apiVersion: v1
kind: ConfigMap
metadata:
  name: aline-configmap
  namespace: dev
data:
  DDL_AUTO: "create-only"
  DB_PORT: "3306"
  PORTAL_ADMIN: "3200"
  PORTAL_DASHBOARD: "3400"
  PORTAL_LANDING: "3600"

