{{- range .Values.Services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: {{ .Values.container.protocol }}
  type: {{ .Values.container.type }}
  selector:
    app: {{ .Values.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.repoAddress }}/{{ .Values.namespace }}-aline-{{ .Values.name }}-mg:{{ .Values.appVersion }}
        # imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: aline-configmap
          - secretRef:
              name: aline-secrets
        ports:
        - containerPort: {{ .Values.container.port }}
          name: {{ .Values.name }}
      restartPolicy: {{ .Values.container.restartPolicy }}
---
{{- end }}