apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.appPort }}
    targetPort: {{ .Values.appPort }}
    protocol: TCP
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.repoAddress }}/aline-{{ .Values.appName }}-mg:{{ .Values.appVersion }}
        # imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: aline-configmap
          - secretRef:
              name: aline-secrets
        ports:
        - containerPort: {{ .Values.appPort }}
          name: {{ .Values.appName }}
      restartPolicy: {{ .Values.restartPolicy }}