apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aline-ingress
  labels:
    name: aline-ingress
    namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.hostname }}
    - http:
        paths:
        - pathType: Prefix
          path: /users/registration
          backend:
            service:
              name: ms-user
              port: 
                number: {{ .Values.userPort }}
        - pathType: Prefix
          path: /login
          backend:
            service:
              name: ms-user
              port:
                number: {{ .Values.userPort }}
        - pathType: Prefix
          path: /applications
          backend:
            service:
              name: ms-underwriter
              port:
                number: {{ .Values.underwriterPort }}  
        - pathType: Prefix
          path: /banks
          backend:
            service:
              name: ms-bank
              port:
                number: {{ .Values.bankPort }}
        - pathType: Prefix
          path: /branches
          backend:
            service:
              name: ms-bank
              port:
                number: {{ .Values.bankPort }}
        - pathType: Prefix
          path: /transactions
          backend:
            service:
              name: ms-transaction
              port:
                number: {{ .Values.transactionPort }}