# VALUES

# TAGS
tags:
  ingress: true
  namespaces: true
  csi-driver: true

namespace: ${BUILD_BRANCH}
replicaCount: 1
restartPolicy: Always

dbPort: 3306

secretsType: "opaque"

Secrets:
  DB_USERNAME: ""
  DB_PASSWORD: ""
  DB_NAME: ""
  DB_HOST: ""
  APP_SERVICE_HOST: ""
  APP_USER_ACCESS_KEY: ""
  APP_USER_SECRET_KEY: ""
  JWT_SECRET_KEY: ""
  ENCRYPT_SECRET_KEY: ""
  S3_TEMPLATE_BUCKET: ""
    
Services:
  - name: ms-bank
    image: ${IMAGE_REPO}:${BUILD_BRANCH}-aline-bank-mg:${BUILD_ID}
    replicas: 1
    container:
      name: ms-bank
      port: 8083
      protocol: TCP
      type: ClusterIP
      restartPolicy: Always
      path: '/(members|banks|branches).*'
  - name: ms-transaction
    image: ${IMAGE_REPO}:${BUILD_BRANCH}-aline-transaction-mg:${BUILD_ID}
    replicas: 1
    container:
      name: ms-transaction
      port: 8073
      protocol: TCP
      type: ClusterIP
      restartPolicy: Always
      path: '/(transactions/?.*|(members|accounts)/.+/transactions)'
  - name: ms-underwriter
    image: ${IMAGE_REPO}:${BUILD_BRANCH}-aline-underwriter-mg:${BUILD_ID}
    replicas: 1
    container:
      name: ms-underwriter
      port: 8071
      protocol: TCP
      type: ClusterIP
      restartPolicy: Always
      path: '/(applicants|applications).*'
  - name: ms-user
    image: ${IMAGE_REPO}:${BUILD_BRANCH}-aline-user-mg:${BUILD_ID}
    replicas: 1
    container:
      name: ms-user
      port: 8070
      protocol: TCP
      type: ClusterIP
      restartPolicy: Always
      path: '/(users|login).*'

adminPort: 3000
dashboardPort: 3400
landingPort: 3800