apiVersion: v1
kind: ConfigMap
metadata:
  name: aline-configmap
  namespace: {{ .Values.namespace | quote }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.rootPassword | quote }}
  MYSQL_DATABASE: "alinedb"
  DDL_AUTO: "create-only"
  DB_USERNAME: {{ .Values.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.rootPassword | quote }}
  DB_HOST: {{ .Values.dbHostAddress | quote }}
  DB_PORT: {{ .Values.dbPort | quote }}
  DB_NAME: "alinedb"
  S3_TEMPLATE_BUCKET: {{ .Values.s3TemplateBucket | quote }}
  PORTAL_ADMIN: {{ .Values.admin | quote }}
  PORTAL_DASHBOARD: {{ .Values.dashboard | quote }}
  PORTAL_LANDING: {{ .Values.landing | quote }}

