# Using helm -range function for loop to loop through each of the Service microservices.
{{- range .Values.Services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .container.port }}
      targetPort: {{ .container.port }}
      protocol: {{ .container.protocol }}
  type: {{ .container.type }}
---
{{- end }}