apiVersion: v1
kind: Secret
metadata:  
  name: ms-secret
type: Opaque
stringData:
  DB_PORT: "3306"
  DB_NAME: "alinedb_ln"
  DB_HOST: aline-database-instance.cwf9bmeqnzq2.us-east-1.rds.amazonaws.com
  APP_SERVICE_HOST: status.hostIP 
  ENCRYPT_SECRET_KEY: ThisIsAGreatSecretKey!!!
  JWT_SECRET_KEY: 21b4054a-1c75-4e8a-aacd-93aaaad92e19
  APP_USER_ACCESS_KEY: QUtJQTNLTlFDQVlSTVZVUzRIWEg=
  APP_USER_SECRET_KEY: NXFjdlJNU2FnT0pJL3liaDBaRWxUeUliZTN2bTZnUzZiWjl5U3MrMw==
  DB_USERNAME: YWxpbmVkYmxu
  DB_PASSWORD: YWxpbmVkYmxu

