---
- hosts: localhost
  become: false

  vars_files:
  - ../vars/static_vars.yml

  tasks:
    - name: get Terraform networking variables
      fetch_terraform_backend_outputs:
        bucket: "jenkins-state-nightwalkers"
        object: "eu-west-1/networking.tfstate"
      register: networking
    - name: filter vpc id
      debug:
        msg: "{{ networking.vars.katapult_cloud_vpc_id }}"